### ISSUE TITLE
Pipeline for initial release.

### ISSUE THREAD

**Issue by ramantehlan** [pydatadelhi/old_website_2#1]
This is the Pipeline for the first release of the PyData-Delhi Site. Before you can pick up the tasks, please make sure you read the following guidelines properly.

1. Read the `README.md` very carefully and thoroughly.
2. You can find the layouts in [temp_design](https://github.com/pydatadelhi/pydatadelhi.github.io/tree/develop/static/tmp_desing), if you find anything confusing in it, you can ask for it in `PyDD Web Dev` telegram group. 
3. It is a responsive site, with a mobile-first approach.

Here is the list of task preceded with their id: 

- [x] Design the architecture for the site, like the build system etc. 
- [x] Add all the pages and menu. (Home, Archive, Blog etc...) 
- [x] **`#1`** Creating a common CSS file and documenting it. (For keeping the same design all over the site) [small design system]
- [x] **`#2`** Adding common bottom(footer) section. 
- [ ] **`#3`** Develop the following pages.
     - [x] **`#3ho`** Home.
     - [x] **`#3co`** Conference. 
     - [ ] **`#3ar`** Archive. 
     - [ ] **`#3bo`** Blog.
     - [x] **`#3sp`** Sponsor.
     - [ ] **`#3vo`** Volunteer.
     - [ ] **`#3na`** News.
     - [ ] **`#3te`** Team.
     - [x] **`#3co`** Contact.
- [ ] **`#4`** Using *meetup.com* API, fetch the last x meetup data. 

`By this point, the site will be ready to push it to production`

To improve the performance of the site following steps should be taken.

- [ ] **`#p-1`** Add `manifest.json` to the project.
- [ ] **`#p-2`** Add service worker for caching.

Both the above lists are subject to updates, and each step can be further divided by you. You can choose the task you would like to work on by simply replying to this issue with the task id.

if at any point you feel you need assistance you can message the community on telegram, or ask it here.

**Comment by sakshivij** [comment]
#1

**Comment by codekhal** [comment]
I am working on #3ho for now! Will shoot a PR soon for your review.

**Comment by bymayanksingh** [comment]
I am working on #3co & #2.

**Comment by bymayanksingh** [comment]
@codekhal are you working on navigation header?

**Comment by codekhal** [comment]
@code-monk08 Yes, in my next PR

**Comment by bymayanksingh** [comment]
I have kept texts, font & other component styling for last, once all the layouts are implemented, will style them consistently.

All are nearly done
Conference Page #3co
Sponsorship Page #sp
Common Footer #2

adding them in my PR

**Comment by bymayanksingh** [comment]
Working on Archive Page now.

**Comment by code-monk08** [comment]
Working on Home Page.

**Comment by ramantehlan** [comment]
We will probably have to design a new pipeline or update this. As it's outdated now.

**Comment by codeweb-stack** [comment]
Hi Raman,

Great to hear from you about the new project on pydata.
If there is  something to do as a volunteer on this project.
I will do as much as I can.

Thanks & Regards
Priyanshu Krishnan
(+91-7905484371)
       Github <https://github.com/codeweb-stack>
Linkedin Profile <https://www.linkedin.com/in/priyanshu-krishnan/>

**Comment by ramantehlan** [comment]
@codeweb-stack I have deleted the comment you posted because it exposed your mobile number publicly. 

Thank you for volunteering for this. If you want, you can take the lead on this and come up with the tech stack and the layout we can use.

**Comment by priyanshu-247** [comment]
Sorry it was sent via email that's why its taken signature.

**Comment by priyanshu-247** [comment]
I will suggest Flutter & Firebase for rapid development tech stack . 
I will be making layout on basis of pages in https://hoverboard-master.firebaseapp.com.

**Comment by sanketverma1704** [comment]
> I will suggest Flutter & Firebase for rapid development tech stack .
> I will be making layout on basis of pages in https://hoverboard-master.firebaseapp.com.

This looks good to me. What do you think @ramantehlan ?
Cc: @Arsh23 @techedlaksh

**Comment by ramantehlan** [comment]
This tech stack is good if we want a site for a conference or something. I like the design for it.

However, the aim now is to create a landing page for PyData Delhi, which is easy to maintain and low cost. We want something for the long term. 

What I had in mind is to use a static site generator like gatsby or Hugo, that I think is easy to maintain and can be done quickly with less efforts.

**Comment by priyanshu-247** [comment]
Yup Gatsby will be much useful for rapid static site build.
Gatsby plugin for meetup.com available at https://www.gatsbyjs.org/packages/gatsby-source-meetup/
So we can seamlessly update website with pydata meetup data.

**Comment by ramantehlan** [comment]
That sounds promising, we can go with this.
